#Follow the steps for installing Git

sudo yum install curl-devel expat-devel gettext-devel openssl-devel zlib-devel

sudo yum remove git

wget https://mirrors.edge.kernel.org/pub/software/scm/git/git-{VERSION}.tar.gz

tar -xf git-{VERSION}.tar.gz

cd git-{VERSION}

sudo yum groupinstall "Development Tools"

sudo yum install curl-devel expat-devel gettext-devel openssl-devel perl-devel zlib-devel

make prefix=/usr/local all

sudo make prefix=/usr/local install

git --version

#if still not happens add it to the path 

echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bashrc

source ~/.bashrc

---

trigger:
  - main

pool: MyA4VMPool

variables:
  imageName: 'prajwalp7295/nodeapp'

steps:
  - task: Docker@2
    displayName: Build and push an image
    inputs:
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: dockerfile
      containerRegistry: dockerhub

  - task: CopyFiles@2
    displayName: 'Copy manifest file'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: 'deploymentservice.yml'  # Specify the name of your manifest file
      TargetFolder: '$(Pipeline.Workspace)'  

  - task: KubernetesManifest@0
    displayName: 'Deploy to Kubernetes'
    inputs:
      action: deploy
      kubernetesServiceConnection: 'k8s'
      manifests: |
        $(Pipeline.Workspace)/deploymentservice.yml