trigger:
  - main

pool: MyA4VMPool

variables:
  imageName: 'prajwalp7295/nodeapp'

steps:
  - task: Docker@2
    displayName: Build and push an image
    inputs:
      repository: $(imageName)
      command: buildAndPush
      Dockerfile: dockerfile
      containerRegistry: DockerHubSvc

  - task: CopyFiles@2
    displayName: 'Copy manifest file'
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: 'deploymentservice.yml'  
      TargetFolder: '$(Pipeline.Workspace)'  

  - task: KubernetesManifest@0
    displayName: 'Deploy to Kubernetes'
    inputs:
      action: deploy
      kubernetesServiceConnection: 'K8sSvc'
      manifests: |
        $(Pipeline.Workspace)/deploymentservice.yml
      namespace: prajwal