---
apiVersion: v1
data:
  prajwal.conf: |
    Hello there! This is Prajwal's conf file.
kind: ConfigMap
metadata:
  name: prajwal-configmap
  namespace: prajwal
---
apiVersion: v1
kind: Secret
metadata:
  name: pp-secret-1
  namespace: prajwal
type: Opaque
data:
  username: prajwal
  password: Pass@1234

 

---

 


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment-pp-1
  namespace: prajwal
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp 
    spec:
      containers:
      - name: nodeserver
        image: thetips4you/nodeapp:latest
        ports:
        - containerPort: 3000
        volumeMounts:
         - name: testconfigmap
           mountPath: "/tmp/config" 
         - name: testsecret
           mountPath: /tmp/mysecrets
      volumes:
        - name: testconfigmap
          configMap:
            name: prajwal-configmap
            items:
              - key: prajwal.conf
                path: prajwal.conf
        - name: testsecret
          secret:
            secretName: pp-secret-1

 

---

 

 

apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service-pp-1
  namespace: prajwal
spec:
  selector:
    app: nodeapp 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31122
